export const SYS_FONTS = [
  { label: 'Arial', value: 'Arial' },
  { label: 'Microsoft jas black', value: 'Microsoft Yahei' },
  { label: 'song typeface', value: 'SimSun' },
  { label: 'blackbody', value: 'SimHei' },
  { label: 'Regular script', value: 'KaiTi' },
  { label: 'The new song typeface', value: 'NSimSun' },
  { label: 'Imitation song dynasty style typeface ', value: 'FangSong' },
  { label: 'Party b to', value: 'PingFang SC' },
  { label: 'Chinese blackbody', value: 'STHeiti' },
  { label: 'Chinese regular script', value: 'STKaiti' },
  { label: 'Chinese song typeface', value: 'STSong' },
  { label: 'Chinese imitation song dynasty style typeface', value: 'STFangSong' },
  { label: 'HuaWenZhong song', value: 'STZhongSong' },
  { label: 'Chinese amber', value: 'STHupo' },
  { label: 'HuaWenXin wei', value: 'STXinwei' },
  { label: 'Chinese official script', value: 'STLiti' },
  { label: 'Chinese travel model', value: 'STXingkai' },
  { label: 'Holly blackbody', value: 'Hiragino Sans GB' },
  { label: 'Lanting black', value: 'Lantinghei SC' },
  { label: 'It happened that body', value: 'Hanzipen SC' },
  { label: 'Your opponent body', value: 'Hannotate SC' },
  { label: 'Song typeface', value: 'Songti SC' },
  { label: 'The dolls body', value: 'Wawati SC' },
  { label: 'Travel model', value: 'Xingkai SC' },
  { label: 'round', value: 'Yuanti SC' },
  { label: 'HuaWenXi black', value: 'STXihei' },
  { label: 'end', value: 'YouYuan' },
  { label: 'Official script', value: 'LiSu' },
]

export const WEB_FONTS = [
  { label: 'In the black', value: 'In the black' },
  { label: 'Warehouse ear small balls', value: 'Warehouse ear small balls' },
  { label: 'Optimal set title', value: 'Optimal set title' },
  { label: 'Peak Octavia body', value: 'Peak Octavia body' },
  { label: 'Taken figure fashionable small cube', value: 'Taken figure fashionable small cube' },
  { label: 'Standing cool and happy', value: 'Standing cool and happy' },
  { label: 'The word system of district xi vein body', value: 'The word system of district xi vein body' },
  { label: 'Material market kangkang body', value: 'Material market kangkang body' },
  { label: 'Material market and cool the body', value: 'Material market and cool the body' },
  { label: 'Cattle round body', value: 'Cattle round body' },
  { label: 'Sharp word mantra', value: 'Sharp word mantra' },
]