export const enum KEYS {
  C = 'C',
  X = 'X',
  Z = 'Z',
  Y = 'Y',
  A = 'A',
  G = 'G',
  L = 'L',
  F = 'F',
  D = 'D',
  B = 'B',
  P = 'P',
  MINUS = '-',
  EQUAL = '=',
  DIGIT_0 = '0',
  DELETE = 'DELETE',
  UP = 'ARROWUP',
  DOWN = 'ARROWDOWN',
  LEFT = 'ARROWLEFT',
  RIGHT = 'ARROWRIGHT',
  ENTER = 'ENTER',
  SPACE = ' ',
  TAB = 'TAB',
  BACKSPACE = 'BACKSPACE',
  ESC = 'ESCAPE',
  PAGEUP = 'PAGEUP',
  PAGEDOWN = 'PAGEDOWN',
  F5 = 'F5',
}

export const HOTKEY_DOC = [
  {
    type: 'general',
    children: [
      { label: 'shear', value: 'Ctrl + X' },
      { label: 'copy', value: 'Ctrl + C' },
      { label: 'paste', value: 'Ctrl + V' },
      { label: 'Quick copy and paste ', value: 'Ctrl + D' },
      { label: 'Future generations', value: 'Ctrl + A' },
      { label: 'undo', value: 'Ctrl + Z' },
      { label: 'restore', value: 'Ctrl + Y' },
      { label: 'delete', value: 'Delete / Backspace' },
      { label: 'multi-select', value: 'Hold down the Ctrl or Shift' },
      { label: 'print', value: 'Ctrl + P' },
      { label: 'Close Windows', value: 'ESC' },
    ],
  },
  {
    type: 'The slide show',
    children: [
      { label: 'From the beginning slide show ', value: 'F5' },
      { label: 'Starting from the current slide show', value: 'Shift + F5' },
      { label: 'Switch back ', value: '↑ / ← / PgUp' },
      { label: 'Switch on the next page', value: '↓ / → / PgDown' },
      { label: 'Switch on the next page', value: 'Enter / Space' },
      { label: 'Exit screening', value: 'ESC' },
    ],
  },
  {
    type: 'Slide editor',
    children: [
      { label: 'A new slide', value: 'Enter' },
      { label: 'Move the canvas', value: 'Space + The mouse to drag and drop' },
      { label: 'Zoom the canvas', value: 'Ctrl + The mouse wheel' },
      { label: 'Zoom the canvas', value: 'Ctrl + =' },
      { label: 'To reduce the canvas', value: 'Ctrl + -' },
      { label: 'To adapt the canvas to the current screen', value: 'Ctrl + 0' },
      { label: 'The previous page（Not selected elements）', value: '↑ / ←' },
      { label: 'The next page（Not selected elements）', value: '↓ / →' },
      { label: 'The previous page', value: 'Roll on the mouse / PgUp' },
      { label: 'The next page', value: 'The mouse scroll down/ PgDown' },
    ],
  },
  {
    type: 'Element operation',
    children: [
      { label: 'mobile', value: '↑ / ← / ↓ / →' },
      { label: 'lock', value: 'Ctrl + L' },
      { label: 'combination', value: 'Ctrl + G' },
      { label: 'Cancel the combination', value: 'Ctrl + Shift + G' },
      { label: 'Top layer', value: 'Alt + F' },
      { label: 'Buy the underlying', value: 'Alt + B' },
      { label: 'Lock wide high percentage', value: 'Hold down the Ctrl or Shift' },
      { label: 'Create a level / Vertical lines', value: 'Hold down the Ctrl or Shift' },
      { label: 'Switch the focus element', value: 'Tab' },
      { label: 'Confirm the picture cut', value: 'Enter' },
    ],
  },
  {
    type: 'Form editor',
    children: [
      { label: 'Focus to the next cell', value: 'Tab' },
      { label: 'Insert a line above us', value: 'Ctrl + ↑' },
      { label: 'Insert a line at the bottom', value: 'Ctrl + ↓' },
      { label: 'Insert a column on the left side', value: 'Ctrl + ←' },
      { label: 'Insert a column on the right side', value: 'Ctrl + →' },
    ],
  },
  {
    type: 'The chart data editor',
    children: [
      { label: 'Focus on the next line', value: 'Enter' },
    ],
  },
  {
    type: 'Text editing',
    children: [
      { label: 'bold', value: 'Ctrl + B' },
      { label: 'italics', value: 'Ctrl + I' },
      { label: 'The underline', value: 'Ctrl + U' },
      { label: 'Delete the line', value: 'Ctrl + D' },
    ],
  },
]